name: Release

on:
  pull_request:
    types: [ closed ]

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: 0
      - uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
